# Generated by Django 6.0 on 2026-02-23 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='connection',
            name='unique_profile_application_connection',
        ),
        migrations.RemoveConstraint(
            model_name='connection',
            name='unique_granted_connection_per_user_application',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='application',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Connection',
        ),
    ]
