# Generated by Django 6.0 on 2026-02-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_application_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='consent',
            name='uniq_profile_app_consent',
        ),
        migrations.AddConstraint(
            model_name='consent',
            constraint=models.UniqueConstraint(fields=('profile', 'application'), name='uniq_consent_profile_application'),
        ),
    ]
