# Generated by Django 6.0 on 2026-02-21 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_consent_uniq_profile_app_consent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=32)),
                ('new_status', models.CharField(blank=True, max_length=32)),
                ('action', models.CharField(choices=[('grant', 'Grant'), ('deny', 'Deny'), ('revoke', 'Revoke'), ('connect', 'Connect')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_audit_events', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_audit_events', to='profiles.application')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_audit_events', to='profiles.profile')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', 'application', 'created_at'], name='profiles_co_profile_4b81cc_idx')],
            },
        ),
    ]
