# Generated by Django 6.0 on 2026-02-23 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_consentauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id_snapshot', models.IntegerField(blank=True, null=True)),
                ('profile_name_snapshot', models.CharField(max_length=80)),
                ('consents_deleted_count', models.PositiveIntegerField(default=0)),
                ('action', models.CharField(choices=[('delete', 'Delete')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['actor', 'created_at'], name='profiles_pr_actor_i_5cc7f4_idx'), models.Index(fields=['profile_id_snapshot', 'created_at'], name='profiles_pr_profile_add2bb_idx')],
            },
        ),
    ]
