# Generated by Django 6.0 on 2026-02-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profileauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='api_key_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
