# Generated by Django 6.0 on 2026-02-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_application_api_key_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='consent_token_hash',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
    ]
