# Generated by Django 6.0 on 2026-02-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_consent_consent_token_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='allowed_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='consent',
            name='consent_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
